[tool.poetry]
name = "verba-group"
version = "0.1.0"
description = ""
authors = ["love_cube <ahapka1@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
scrapy = "^2.13.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
